#!/usr/bin/env python
"""Stamp code-provenance metadata onto an already-generated trajectory dataset.

The per-trajectory ``manifest.csv`` files already capture *sampling* metadata
(seed, cell, losses).  What they lack is *code* provenance: which git commit,
which generator script, which MACE checkpoint produced the data.  This tool
fills that gap so any output dir can be traced back to an exact, re-runnable
state of the repo.

For every ``<compound>_<mp_id>_trajectories/`` dir under ``--root`` it writes a
``PROVENANCE.json`` and (with ``--stamp-manifest``) appends provenance columns
to ``manifest.csv``.  Both operations are NON-DESTRUCTIVE and IDEMPOTENT:

  * manifest.csv is backed up to manifest.csv.bak before the first edit, and
    a dir already carrying the provenance columns is skipped.
  * PROVENANCE.json is skipped if present unless ``--force``.

provenance_confidence:
  exact          the dataset was generated by the committed ``--gen-script`` at
                 this git_sha (use for big_exp_liquid and the tail re-run).
  reconstructed  the generator was committed AFTER the data was produced, so
                 the SHA is the closest faithful snapshot, not byte-exact (use
                 for the original big_exp bulk).

Examples
--------
# Original bulk (best-effort), JSON only first to eyeball it:
python stamp_provenance.py --root /pscratch/.../big_exp \\
    --gen-script safemem_generate_mace_perl.py \\
    --confidence reconstructed --source-tag mace_big_v1 \\
    --regimes amorphous,SRO,MRO,LRO,nanocrystalline,crystalline_30 --dry-run

# Then for real, also stamping the manifests:
python stamp_provenance.py --root /pscratch/.../big_exp \\
    --gen-script safemem_generate_mace_perl.py \\
    --confidence reconstructed --source-tag mace_big_v1 \\
    --regimes amorphous,SRO,MRO,LRO,nanocrystalline,crystalline_30 \\
    --stamp-manifest

# Liquid (exact):
python stamp_provenance.py --root /pscratch/.../big_exp_liquid \\
    --gen-script generate_liquid_perl.py \\
    --confidence exact --source-tag mace_liquid_v1 \\
    --regimes liquid --stamp-manifest
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

PROV_COLUMNS = ("git_sha", "gen_script_sha256", "provenance_confidence",
                "stamped_at")


def _run_git(args: list[str], cwd: Path) -> str | None:
    try:
        out = subprocess.run(["git", *args], cwd=cwd, capture_output=True,
                             text=True, check=True)
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def build_record(args) -> dict:
    repo = Path(args.gen_script).resolve().parent
    git_sha = args.sha or _run_git(["rev-parse", "HEAD"], repo) or "UNKNOWN"
    record = {
        "dataset_root": str(Path(args.root).resolve()),
        "git_sha": git_sha,
        "git_describe": _run_git(["describe", "--tags", "--always", "--dirty"],
                                  repo),
        "git_dirty": bool(_run_git(["status", "--porcelain"], repo)),
        "tricor": f"in-repo @ {git_sha}",
        "gen_script": str(Path(args.gen_script).resolve()),
        "gen_script_sha256": _sha256(Path(args.gen_script)),
        "mace_model": args.mace_model,
        "mace_dtype": args.mace_dtype,
        "source_tag": args.source_tag,
        "regimes": args.regimes.split(","),
        "seed_scheme": args.seed_scheme,
        "provenance_confidence": args.confidence,
        "stamped_at": args.stamped_at or _dt.datetime.now().isoformat(
            timespec="seconds"),
        "stamped_by": os.getenv("USER", "unknown"),
        "stamper_version": 1,
    }
    if args.confidence == "reconstructed":
        record["provenance_note"] = (
            "Generator committed AFTER this data was produced; git_sha is the "
            "closest faithful snapshot of the as-built code, not byte-exact. "
            "See dataset-level PROVENANCE.md.")
    return record


def stamp_manifest(manifest: Path, record: dict) -> str:
    """Append PROV_COLUMNS to every row of manifest.csv (idempotent)."""
    with manifest.open() as f:
        reader = csv.reader(f)
        rows = list(reader)
    if not rows:
        return "empty"
    header = rows[0]
    if all(c in header for c in PROV_COLUMNS):
        return "already-stamped"
    backup = manifest.with_suffix(".csv.bak")
    if not backup.exists():
        backup.write_text(manifest.read_text())
    add_vals = [record["git_sha"], record["gen_script_sha256"],
                record["provenance_confidence"], record["stamped_at"]]
    new_header = header + list(PROV_COLUMNS)
    with manifest.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(new_header)
        for row in rows[1:]:
            w.writerow(row + add_vals)
    return "stamped"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", required=True, type=Path,
                    help="dataset root containing *_trajectories/ dirs")
    ap.add_argument("--gen-script", required=True,
                    help="path to the generator script (its repo gives git_sha)")
    ap.add_argument("--confidence", required=True,
                    choices=["exact", "reconstructed"])
    ap.add_argument("--source-tag", required=True,
                    help="SOURCE_TAG written into the NPZs by the generator")
    ap.add_argument("--regimes", required=True,
                    help="comma-separated regime list the run produced")
    ap.add_argument("--mace-model", default="medium-mpa-0")
    ap.add_argument("--mace-dtype", default="float32")
    ap.add_argument("--seed-scheme",
                    default="rng_seed = BASE_SEED(2_000_000) + cif_idx*1000 + idx")
    ap.add_argument("--sha", default=None,
                    help="override git_sha (default: git rev-parse HEAD)")
    ap.add_argument("--stamped-at", default=None,
                    help="override ISO timestamp (default: now)")
    ap.add_argument("--stamp-manifest", action="store_true",
                    help="also append provenance columns to each manifest.csv")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing PROVENANCE.json")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if not args.root.is_dir():
        sys.exit(f"--root not found: {args.root}")
    if not Path(args.gen_script).is_file():
        sys.exit(f"--gen-script not found: {args.gen_script}")

    record = build_record(args)
    print("Provenance record:")
    print(json.dumps(record, indent=2))
    print()

    dirs = sorted(p for p in args.root.glob("*_trajectories") if p.is_dir())
    print(f"{len(dirs)} trajectory dirs under {args.root}\n")

    n_json = n_json_skip = n_manifest = n_manifest_skip = n_no_manifest = 0
    for d in dirs:
        prov = d / "PROVENANCE.json"
        if prov.exists() and not args.force:
            n_json_skip += 1
        elif args.dry_run:
            n_json += 1
        else:
            prov.write_text(json.dumps({**record, "dir": d.name}, indent=2))
            n_json += 1

        if args.stamp_manifest:
            manifest = d / "manifest.csv"
            if not manifest.is_file():
                n_no_manifest += 1
            elif args.dry_run:
                n_manifest += 1
            else:
                status = stamp_manifest(manifest, record)
                if status == "stamped":
                    n_manifest += 1
                else:
                    n_manifest_skip += 1

    tag = " (dry-run, nothing written)" if args.dry_run else ""
    print(f"PROVENANCE.json : {n_json} written, {n_json_skip} skipped "
          f"(exist){tag}")
    if args.stamp_manifest:
        print(f"manifest.csv    : {n_manifest} stamped, {n_manifest_skip} "
              f"already-stamped, {n_no_manifest} missing{tag}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
